### ISSUE TITLE
psconfig translate don't validate some hostnames

### ISSUE THREAD

**Issue by tonin** [perfsonar/psconfig#21]
The JSON validation library used by `psconfig translate` refuses to use hostnames that are not considered valid.  The validation seems to refuses some TLD it doesn't know about.

Example: `mp10.tnc18.edu.pert` will get refused, but `mp10.tnc18.pert.edu` is working fine.  Even though the first one actually resolves locally and the second one doesn't.

**Comment by arlake228** [comment]
Fixed this in latest commit. I overrode the hostname validation of the JSON::Validator, which uses Domain::Validate::is_domain, with a call to Domain::Validate::is_hostname. The first validates TLDs, the second does not. I could have alternatively changed the schema files to use a custom regex instead of the built-in hostname format, but a) i think I'll forget that over time and b)the schema serves documentation purposes and it is much cleaner in its current form.
